# fly.toml app configuration file generated for giftcarttools-weathered-haze-5842 on 2024-08-08T17:55:42+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'giftcarttools-weathered-haze-5842'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
