# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94997e00ee5a5fe267ce8482dc171fab"
name = "giftcart-tools-staging"
handle = "giftcart-tools-staging-1"
application_url = "https://intervention-associations-km-kill.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xpressbees-giftcart.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://intervention-associations-km-kill.trycloudflare.com/auth/callback",
  "https://intervention-associations-km-kill.trycloudflare.com/auth/shopify/callback",
  "https://intervention-associations-km-kill.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
