# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Giftcart Tools"
client_id = "19ef1a6130a5848727366b184b798480"
application_url = "https://sherman-columbus-admission-absorption.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sherman-columbus-admission-absorption.trycloudflare.com/auth/callback",
  "https://sherman-columbus-admission-absorption.trycloudflare.com/auth/shopify/callback",
  "https://sherman-columbus-admission-absorption.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xpressbees-giftcart.myshopify.com"
