# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "408bb0f74718417100c7280c8620d638"
name = "giftcart_tools"
application_url = "https://discussions-prospects-ss-band.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xpressbees-giftcart.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://discussions-prospects-ss-band.trycloudflare.com/auth/callback",
  "https://discussions-prospects-ss-band.trycloudflare.com/auth/shopify/callback",
  "https://discussions-prospects-ss-band.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
